// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  introSidebar: [
    'intro',
    'getting_started',
    {
      type: 'category',
      label: 'Technology',
      items: [
        {type: 'autogenerated', dirName: 'technology'}
      ]
    },
    'hardware',
    {
      type: 'category',
      label: 'Feeding',
      items: [
        {type: 'autogenerated', dirName: 'feeding'}
      ]
    },
    {
      type: 'category',
      label: 'Decoder Clients',
      items: [
        {type: 'autogenerated', dirName: 'decoders'}
      ]
    },
    {
      type: 'category',
      label: 'Airwaves OS',
      items: [
        {type: 'autogenerated', dirName: 'aros'}
      ]
    },
    {
      type: 'category',
      label: 'Airframes Backend',
      items: [
        {type: 'autogenerated', dirName: 'backend'}
      ]
    },
    {
      type: 'category',
      label: 'Community',
      items: [
        'contributing', 'chat', 'team'
      ]
    },
  ],
};

module.exports = sidebars;
