// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  introSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Technology',
      items: [
        {type: 'autogenerated', dirName: 'technology'}
      ]
    },
    'getting_started',
    {
      type: 'category',
      label: 'Community',
      items: [
        'team', 'chat'
      ]
    },
  ],
};

module.exports = sidebars;
