name: Yarn Test CI

on:
  workflow_dispatch:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 
      uses: actions/setup-node@v4
      with:
        cache: yarn
    - run: yarn install --frozen-lockfile
    - run: yarn test
